angular.module('app',['ngRoute','aside','header','index','login','http','api','web_api'])
    .config(['$routeProvider',function($routeProvider){
        $routeProvider
            .when('/',{
                template:'<ngl-aside></ngl-aside><ngl-index></ngl-index>',
            })
            .when('/index',{
                redirectTo:'/'
            })
            .when('/login',{
                template:'<ngl-login></ngl-login>',
            })
            .otherwise({
                templateUrl:'/src/html/404.html'
            })
    }])